"""m-1

Revision ID: 959fb298c26b
Revises: 
Create Date: 2021-01-20 12:09:48.609292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959fb298c26b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('confirm_password', sa.String(length=20), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('sid', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.String(length=40), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('chat_room', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('role')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=40), nullable=True),
    sa.Column('sid', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('create_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room')
    )
    op.create_table('join',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('sid', sa.String(length=50), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('sid', sa.String(length=50), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave')
    op.drop_table('join')
    op.drop_table('create_room')
    op.drop_table('room_dict')
    op.drop_table('chat')
    op.drop_table('admin_role')
    op.drop_table('user')
    # ### end Alembic commands ###
